# Generated by Django 5.0.4 on 2024-05-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='eid',
            field=models.IntegerField(blank=True, null=True, verbose_name='employee ID'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ename',
            field=models.CharField(blank=True, max_length=50, verbose_name='employee name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='esalary',
            field=models.FloatField(default=0.0, verbose_name='employee salary'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='user', max_length=150, unique=True, verbose_name='username'),
        ),
    ]
