# Generated by Django 5.0.4 on 2024-05-06 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_eid_customuser_ename_customuser_esalary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='password',
        ),
    ]
